version: 2
updates:
  - commit-message:
      prefix: "Changelog:All"
    directory: /tests
    package-ecosystem: pip
    schedule:
      interval: weekly
  - commit-message:
      prefix: "Changelog:All"
    directory: /
    package-ecosystem: gitsubmodule
    schedule:
      interval: weekly
